### PR TITLE
Refactor Octavia maintenance (SOC-8726)

### PR DESCRIPTION
**Pull request by nicolasbock**
This change pulls the Octavia maintenance sections out into a separate
file and links that file from the CLM and Crowbar Operations manuals.

Signed-off-by: Nicolas Bock <nicolas.bock@suse.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
I haven't figured out yet how to keep the prompts consistent when building the Ardana documentation as opposed to the Crowbar documentation. I'll look whether one can define the prompt macro depending on the life cycle manager.

**Comment by jeremy-moffitt** [comment]
I dont think the prompts are too big an issue, looking at the single page html, `tux` is used in almost 300 places... so that may be ok. I'm surprised at the scope of changes to `soc-operations-maintenance.xml`  is that intentional?

**Comment by nicolasbock** [comment]
I changed a lot of indentations. I don't know if we have a "coding style" for XML, but the indentation was pretty inconsistent.

**Comment by nicolasbock** [comment]
I can revert that of course.

**Comment by jeremy-moffitt** [comment]
If the content is the same (other than embedding the removal of load balancers) I wont scan it for content, but just sanity check spacing, etc... thanks for the info. The CLM docs look fine, building Crowbar next.

**Comment by nicolasbock** [comment]
No content changes

**Pull request merged**
