### PR TITLE
SOC 9 DC files: Update to 2021 stylesheets

### PR DESCRIPTION
**Pull request by ghost**
This updates the SOC 9 docs to the 2021 SUSE branding.

Be aware that if you intend to ship another documentation package update as a MU, this has the potential to break your build. However, @tomschr has already updated the suse-xsl-stylesheets package for most SLE distributions, so I think you should be fine even if you need to make a doc MU.

There's a related PR for SOC 8, see #1327

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
I may be looking in the wrong place, but https://build.suse.de/package/show/SUSE:SLE-12-SP4:Update/suse-xsl-stylesheets  doesnt appear to have been updated in a year... oddly, the SP3 version seems to be more recent https://build.suse.de/package/show/SUSE:SLE-12-SP3:Update/suse-xsl-stylesheets  ... SOC9 is SLE12-SP4 based, SOC8 is SLE12-SP3

**Comment by jeremy-moffitt** [comment]
I see a SLE12-SP4 update in @tomschr  's home space in IBS, linked from the base package, and that has the update... if this has the potential to break an MU its probably best to wait for that to land before merging this.

tagging @gosipyan for visibility as she typically builds the MUs for SOC

**Comment by ghost** [comment]
You're right, for the suse-xsl-stylesheets package, [the MU for 12 SP4](https://maintenance.suse.de/incident/20274/) is still running, whereas [the separate MU for 12 SP3](https://maintenance.suse.de/incident/20273/) is already in. Not sure why.

**Comment by ghost** [comment]
@jeremy-moffitt The MU for suse-xsl-stylesheets is out. It should be safe to merge (both) PRs now.

**Review by jeremy-moffitt — APPROVED** [review]
the SLES12SP4 change has landed, I was able to update daps2docker and build these locally. They look fine to me. approved and merging

**Pull request merged**
