### PR TITLE
fix RHEL installation instructions (bsc#1111503) (bsc#1111533)

### PR DESCRIPTION
**Pull request by csymons-suse**
add "/" to repository location
add missing dependency for RHEL Compute Nodes

### CODE REVIEW

**Comment by KeithMnemonic** [comment]
the libcacard is acutally on the install media, so if the repos are done correctly it will get pulled in automatically but only if you use yum. the notes here just list the 4 rpms and the rpm -U command.  WE should add more context here. something like libcard is needed and should be automtically pulled in when you use yum. If it is not found, you will need to add it manually,.....

**Comment by csymons-suse** [comment]
The instructions preceding this section refer to the CentOS repository and YUM. So your comment must be related to some other process of getting to nova-compute installation. Is that correct? Does this matter to the documentation?

With the edits in this commit, the section reads:
```
The following RPM packages from that location have been tested successfully:
qemu-img-ev-2.6.0-28.el7.10.1.x86_64.rpm
qemu-kvm-common-ev-2.6.0-28.el7.10.1.x86_64.rpm
qemu-kvm-ev-2.6.0-28.el7.10.1.x86_64.rpm
qemu-kvm-tools-ev-2.6.0-28.el7.10.1.x86_64.rpm
libcacard-ev-2.3.0-31.el7_2.21.1.x86_64.rpm

Note that, in the case of migrating from a previous version of these packages, they should be installed using rpm -U FILENAME rather than rpm -i FILENAME.

All of the RPM packages should be installed together and not individually, as shown below:
tux > sudo rpm -Uvh qemu-img-ev-2.6.0-28.el7.10.1.x86_64.rpm \
qemu-kvm-common-ev-2.6.0-28.el7.10.1.x86_64.rpm \
qemu-kvm-ev-2.6.0-28.el7.10.1.x86_64.rpm \
qemu-kvm-tools-ev-2.6.0-28.el7.10.1.x86_64.rpm \
libcacard-ev-2.3.0-31.el7_2.21.1.x86_64.rpm
```
I just added:
```
The RPM package for libcacard-ev is required and should be automatically
pulled in when you use the Yum repo as described above. If this dependency
is not found, it must be installed manually with the qemu-kvm packages.
```
Does that get it?

**Comment by KeithMnemonic** [comment]
Carl,

There are two ways to install packages on RHEL, One is using the "rpm" command and that is what we listed and we specifiy -U. If you are using rpm, it may not pull in libcacard automatically.  This is why you need to specify it with the other packages on one long rpm command. The other way is using the "yum" command This will pull in libcacard auotmatically if it finds it in one of its configured repos

**Comment by csymons-suse** [comment]
One additional change:
```
The RPM package for libcacard-ev is required and should be automatically
pulled in when you use the Yum repo as described above <emphasis role="bold">and</emphasis> you install with the <command>Yum</command> command. If this dependency is not found, you will receive an error message reporting a failed dependency. In this case, the RPM package must be installed manually with the qemu-kvm packages.
```

**Comment by spacefito** [comment]
+1

**Comment by csymons-suse** [comment]
content moved to maintenance/cloud_8 in
https://github.com/SUSE-Cloud/doc-cloud/pull/585

**Pull request closed without merging**
