### PR TITLE
Update ESX documentation for DVS creation (bsc#1142121)

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
Based on feedback from L3 and Boeing, updated the ESX configuration steps for SOC-CLM, specifically around DVS creation

### CODE REVIEW

**Review by KeithMnemonic — CHANGES_REQUESTED** [review]
1) I Think section 27.6 can come before 27.4. 
2) On this confluence page we made some note for Section 27.3 (that apply to 27.11) but i do not see these notes added anywhere.  We should add them before 27.11.
3) Section 9.4.1 typo "User needs to deploy the ovsvapp network resources using the vSphere GUI or by running them neutron-create-ovsvapp-resources.yml playbook" should be the instead of them.
4) Section 9.4.1 should match 27.10, ie DVS are MGMT and TRUNK and not MGMT and ESX-CONF
5) 27.14 path is ~ardana/openstack/ardana/ansible/ardanaencrypt.py

**Comment by jeremy-moffitt** [comment]
> 4. Section 9.4.1 should match 27.10, ie DVS are MGMT and TRUNK and not MGMT and ESX-CONF

Is this simply changing the name from ESX-CONF in the line:
```
         ESX-CONF (DVS and DVPG) connected to ovsvapp eth0 and compute-proxy
         eth0
```
or is there more to it? I don't see a TRUNK reference in 27.10. I see it in 27.11 in my local copy, but not sure I understand whether TRUNK is still "connected to ovsvapp eth0 and compute-proxy eth0" or if the instructions change along with which network it is

**Comment by KeithMnemonic** [comment]
It should be like this https://bugzilla.suse.com/attachment.cgi?id=841225 

MGMT – DVS
  ESX-CONF-PG
  GUEST -PG           - promiscuous mode & forged transmits is enabled in the switch
  MGMT -PG
TRUNK -DVS
  TRUNK -PG          - promiscuous mode & forged transmits is enabled in the switch

so Two DVS MGMT and TRUNK, and 4 PG

**Comment by jeremy-moffitt** [comment]
tweaked it, but I don't think its quite right yet... I'll send you a link

**Comment by KeithMnemonic** [comment]
> tweaked it, but I don't think its quite right yet... I'll send you a link

9.4.1 ESX Resource Requirements item 2 conflicts with  and .27.8.4 so we should remove 27.8.4 or add that option in 9.4.1 

Perhaps the listing under the paragraph beginning with "The following DVS and DVPGs"  could be a table for example

DVS                             PORT GROUPS Assigned to DVS
______________________________________
MANAGEMENT          MANAGEMENT, GUEST,ESX-CONF
TRUNK                        TRUNK

**Comment by KeithMnemonic** [comment]
> > tweaked it, but I don't think its quite right yet... I'll send you a link
> 
> 9.4.1 ESX Resource Requirements item 2 conflicts with and .27.8.4 so we should remove 27.8.4 or add that option in 9.4.1
> 
> Perhaps the listing under the paragraph beginning with "The following DVS and DVPGs" could be a table for example
> 
> DVS PORT GROUPS Assigned to DVS
> 
> MANAGEMENT MANAGEMENT, GUEST,ESX-CONF
> TRUNK TRUNK

the spacing did not come out great but one column is DVSand the other is  PORT GROUPS Assigned to DVS

**Comment by jeremy-moffitt** [comment]
Updated and sent a copy of the pdf... 
bz1142121

Not sure if there were other changes outside of 9.4.1 , if so I may need a reminder

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Pull request merged**
