### PR TITLE
Feature/cluster recovery

### PR DESCRIPTION
**Pull request by taroth21**

### CODE REVIEW

**Comment by aspiers** [comment]
Cool - please can you remind me how to locally generate HTML from this repo so that I can review this branch more visually?

**Comment by aspiers** [comment]
I tried:

    daps -d DC-suse-openstack-cloud-deployment html --single

I got rid of various failures by updating packages to the latest from [IBS `Documentation:Tools`](https://build.suse.de/project/show/Documentation:Tools) but I still get

```
/home/adam/SUSE/cloud/git/doc-cloud/build/.profiled/sles/MAIN.suse-openstack-cloud.xml:26:44: warning: exception "java.io.FileNotFoundException" thrown: Include operation failed, reverting to fallback. Resource error reading file as XML (href='book_cloud_deploy.xml'). Reason: /home/adam/SUSE/cloud/git/doc-cloud/build/profiled/sles/book_cloud_deploy.xml (No such file or directory): /home/adam/SUSE/cloud/git/doc-cloud/build/profiled/sles/book_cloud_deploy.xml (No such file or directory)
/home/adam/SUSE/cloud/git/doc-cloud/build/.profiled/sles/MAIN.suse-openstack-cloud.xml:26:44: fatal: An 'include' failed, and no 'fallback' element was found.
/usr/share/daps/make/validate.mk:26: recipe for target '/home/adam/SUSE/cloud/git/doc-cloud/build/.profiled/sles/.validate' failed
make: *** [/home/adam/SUSE/cloud/git/doc-cloud/build/.profiled/sles/.validate] Error 1
```

Any ideas?

**Comment by taroth21** [comment]
Adam, can you try installing java-devel? Joseph had a similar problem recently, IIRC...

**Comment by jcayouette** [comment]
Yes I fixed this issue by installing java-1_8_0-openjdk-devel

**Comment by aspiers** [comment]
@taroth21 @jcayouette Thanks, installing `java-1_8_0-openjdk-devel` fixed it! Will someone take care of fixing the missing package dependency?

**Pull request merged**
