### PR TITLE
Add Octavia Process monitoring configuration options (SOC-10915)

### PR DESCRIPTION
**Pull request by jeremy-moffitt**

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
soc-10915

**Comment by jeremy-moffitt** [comment]
Just above "Installing the Amphora Image" at https://documentation.suse.com/soc/9/single-html/suse-openstack-cloud-deployment/#id-1.3.7.7.9

**Review by KeithMnemonic — DISMISSED** [review]
LGTM

**Review by yarunachalam — CHANGES_REQUESTED** [review]
add the following lines in [health_manager] section.

**Comment by jeremy-moffitt** [comment]
soc-10915-1
updated per Yoga's feedback

**Review by yarunachalam — APPROVED** [review]
LGTM

**Pull request merged**
