### PR TITLE
Modified the PTF install instructions as per the (SOC-10616)

### PR DESCRIPTION
**Pull request by yarunachalam**
Validated the PTF install instructions and modified as per the comments.

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
soc-10616_0
screenshot of the modified version

**Comment by rtamalin** [comment]
The fixed step 9 looks good above... But possibly step 8 and 9 above should be reverse so that we install the venv on the deployer before doing any actual updating of the nodes...

**Review by rtamalin — APPROVED** [review]
LGTM

**Review by jeremy-moffitt — APPROVED** [review]
LGTM

**Pull request merged**
