### PR TITLE
Moved Monasca deployment to immediately after keystone (SOC-11525)

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
soc-11525

1. moved Monasca up the list to just below keystone
2. added `(Optional)` to the Monasca step description

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
githubs diff of this is terrible... the reality is I moved one section consisting of several hundred lines to earlier in the same file...  I think the fact that different sections use the same docbook tags (para, section, etc...) confuses git :-/

**Comment by jeremy-moffitt** [comment]
[book-deployment_color_en.zip](https://github.com/SUSE-Cloud/doc-cloud/files/6466581/book-deployment_color_en.zip)
the pdf isnt as nicely formatted as the html, but you can see the result of this change as "deploying Monaca" is now section 12.6 , as opposed to 12.19 in the version at https://documentation.suse.com/soc/8/pdf/book-deployment_color_en.pdf

**Comment by yarunachalam** [comment]
In Section 12 - Deploying the Openstack Services - It lists the order of installation. Currently, it is in 17. It should be updated accordingly

**Comment by jeremy-moffitt** [comment]
> In Section 12 - Deploying the Openstack Services - It lists the order of installation. Currently, it is in 17. It should be updated accordingly

I believe I have this fixed... please see attached

[book-deployment_color_en.zip](https://github.com/SUSE-Cloud/doc-cloud/files/6468266/book-deployment_color_en.zip)

**Comment by yarunachalam** [comment]
LGTM

**Review by yarunachalam — APPROVED** [review]

**Pull request merged**
