### PR TITLE
replace empty ESX compatibility guide (noref)

### PR DESCRIPTION
**Pull request by csymons-suse**
the link in ESX Guest OS Support went to an empty form.
Replace with form filled in with proper information.

Remove FIXME:

(cherry picked from commit 877b2d8fcf2434179c9ffa610937a5c6ce68583b)

### CODE REVIEW

**Comment by asettle** [comment]
Same as the comment on https://github.com/SUSE-Cloud/doc-cloud/pull/1054

**Comment by csymons-suse** [comment]
> Same as the comment on #1054
see
https://github.com/SUSE-Cloud/doc-cloud/pull/1054

**Comment by asettle** [comment]
Tracking purposes, response here: https://github.com/SUSE-Cloud/doc-cloud/pull/1054#discussion_r305260625

**Comment by csymons-suse** [comment]
link reworked in https://github.com/SUSE-Cloud/doc-cloud/pull/1052
https://github.com/SUSE-Cloud/doc-cloud/commit/1a222b24

**Pull request merged**
